const SET_ALERT = 'SET_ALERT';
const REMOVE_ALERT = 'REMOVE_ALERT';

const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const REGISTER_FAIL = 'REGISTER_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGOUT = 'LOGOUT';
const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

const USER_LOADED = 'USER_LOADED';
const AUTH_ERROR = 'AUTH_ERROR';


const GET_PROFILE = 'GET_PROFILE';
const GET_PROFILES = 'GET_PROFILES';
const CLEAR_PROFILE = 'CLEAR_PROFILE';
const PROFILE_ERROR = 'PROFILE_ERROR';
const UPDATE_PROFILE = 'UPDATE_PROFILE';
const GET_REPOS = 'GET_REPOS';

const GET_POSTS = 'GET_POSTS';
const POST_ERROR = 'POST_ERROR';
const UPDATE_LIKES = 'UPDATE_LIKES';
const DELETE_POST = 'DELETE_POST';

export {
  SET_ALERT,
  REMOVE_ALERT,
  REGISTER_SUCCESS,
  REGISTER_FAIL,
  USER_LOADED,
  AUTH_ERROR,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  LOGOUT,
  GET_PROFILE,
  GET_PROFILES,
  PROFILE_ERROR,
  CLEAR_PROFILE,
  UPDATE_PROFILE,
  DELETE_ACCOUNT,
  GET_REPOS,
  GET_POSTS,
  POST_ERROR,
  UPDATE_LIKES,
  DELETE_POST,
}